#!/bin/bash

set -e
set -o pipefail

echo $1
if pdf-crop-margins --modifyOriginal --uniformOrderPercent 10 --percentRetain4 30 10 10 30 $1 ; then
    # Crop without gsFix worked
    echo ""
else
    pdf-crop-margins --modifyOriginal --gsFix --uniformOrderPercent 10  --percentRetain4 30 10 10 30 $1
fi

rmapi put $1
